{% set name = "pinecone-plugin-assistant" %}
{% set version = "3.0.3" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/pinecone_plugin_assistant-{{ version }}.tar.gz
  sha256: 53f548ede60a95d79ff48d7865a3d0afd665ced9e77758272e62ba0c6c63bd26

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  number: 0

requirements:
  host:
    - python {{ python_min }}
    - poetry-core
    - pip
  run:
    - python >={{ python_min }},<4.0.0
    - requests >=2.32.3,<3.0.0

test:
  imports:
    - pinecone_plugins.assistant
  commands:
    - pip check
  requires:
    - python {{ python_min }}
    - pip
    # beware of potential circular dependency
    - pinecone

about:
  home: https://www.pinecone.io
  summary: Assistant plugin for Pinecone SDK
  license: Apache-2.0
  license_file: LICENSE.txt
  doc_url: https://docs.pinecone.io/guides/get-started/overview

extra:
  recipe-maintainers:
    - xylar
